# -*- coding: utf-8 -*-
"""Prodigy_ML_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dinesh0110/PRODIGY_ML_01/blob/main/Prodigy_ML_01.ipynb
"""

#import necessary Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df=pd.read_csv('/content/House Price India.csv')
df

df.shape

# Statistical Analysis
df.describe()

df.info()

plt.scatter(df['living area'],df['Price'],color='black')
plt.xlabel('price in (\u20B9)')
plt.ylabel('(living area in sqft)')
plt.title('Price vs Living area')

import seaborn as sns
df=df[["living area", "number of bedrooms", "number of bathrooms","Price"]]
sns.pairplot(df)

sns.heatmap(df.corr(),annot=True)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X = df[["living area", "number of bedrooms", "number of bathrooms"]]
y = df["Price"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean squared error:", mse)
print("R-squared:", r2)

